// <auto-generated />
namespace VirtualAssistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class exercise34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exercise34));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161008502_exercise34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
